### ISSUE TITLE
Chrome New Tab Extension

### ISSUE THREAD

**Issue by jdsimcoe** [jonathontoon/manifest#100]
I've used similar products like Papier (https://getpapier.com/) that have a New Tab Browser extension. I'd love to be able to use Manifest in the New Tab space. There are extensions that hack this but they are clunky and it seems like this would be pretty easy to execute on.

**Comment by adamlaz** [comment]
Could be nice! I just set up that functionality w/ [this existing chrome extension](https://chrome.google.com/webstore/detail/custom-new-tab-url/mmjbdbjnoablegbkcklggeknkfcjkjia?hl=en). Seems to work fine. What would be different as a 'native new tab extension' in Chrome? 

That being said, it seems pretty simple/quick ([blog post tutorial](https://medium.com/@ryanfarney/creating-a-chrome-extension-that-will-open-in-a-new-tab-bc06b7eb54aa)) to get a new tab extension running, especially if just loading a URL. Maybe I'll open a new PR 🎉

**Comment by jonathontoon** [comment]
@adamlaz feel free to take a stab, would love to see an example of it working.

Currently though I see little value in supporting it if it means bloating the app for an implementation that might only work on just Chrome, for example. Ideally if we pursued this the metric for success would be to have it work across Chromium-browsers, Firefox _and_ Safari.

My other concern is this may introduce busy-work for someone who then needs to manage updating the extension in respective browser web stores. But we can cross that bridge when we come to it.

**Comment by pravinxnonzero** [comment]
I can make a simple Open Source Chrome extension - that can replace a new tab with a manifest.app 
if I get more than two request - I will make it happen
