### ISSUE TITLE
Don't confirm memo deletion

### ISSUE THREAD

**Issue by vreon** [jonathontoon/manifest#105]
The `confirm()` dialog displayed when deleting a memo does a great job of preventing accidental deletion, but it's more likely that the user deleted the memo intentionally. Requiring confirmation disrupts the user's flow and can be tedious to interact with (e.g. when deleting several memos).

## Possible Solution
A [snackbar](https://material.io/components/snackbars/) with an Undo button seems like the usual way to do this these days.

**Comment by jonathontoon** [comment]
Thanks for the suggestion @vreon.

While snackbar patterns are nice, and could look neat with Manifest's visual style, I err more on the side of keeping the app as lean as possible. Basically I'm not sure the payoff of creating a custom toast system outweighs a low maintenance dialog system native to every browser.
