### ISSUE TITLE
Investigate performance on Safari

### ISSUE THREAD

**Issue by jonathontoon** [jonathontoon/manifest#107]
## Expected Behavior
It should work.

## Current Behavior
Some folks on [Hacker News](https://news.ycombinator.com/item?id=22094974) suggested someone with up on Safari browsers.

**Comment by jonathontoon** [comment]
Had a look on the most recent build of Safari and can confirm there are some issues with dragging/creating memos relating to `user-select`.

**Comment by pacocoursey** [comment]
Cannot reproduce any issues with creating new notes, dragging notes, or resizing notes on Safari.

Agreed with adding `user-select: none` to each `<textarea>` while dragging is in process though, as it does seem to select existing text inside notes.

**Comment by jonathontoon** [comment]
Closing for now to focus on some more explicitly reported Safari issues.
