### ISSUE TITLE
Convert URLs to links

### ISSUE THREAD

**Issue by rajiv-k** [jonathontoon/manifest#109]
## Expected Behavior
It would be great if the URLs in the note are rendered as "links".

## Current Behavior
URLs are rendered as plain text.

## Possible Solution
https://github.com/SoapBox/linkifyjs/

## Steps to Reproduce (for bugs)
1. Create a new note and paste any URL.

## Your Environment
* Environment name and version (nginx 1.9.1):
* Operating System and version: macOS High Sierra 10.13.6

**Comment by jonathontoon** [comment]
Thanks a lot of the suggestion @rajiv-k! I think this would better discussed in issue #21 for if we introduce the concept of rendered links it should probably be in the context of other types of styled text.

**Comment by januwland** [comment]
Adding my support for this 🆗
