### ISSUE TITLE
Not able to toggle Dark Mode

### ISSUE THREAD

**Issue by abhijitnathwani** [jonathontoon/manifest#112]
Hi,
Thank you for this awesome project! While exploring, I read about the `dark mode` support. However, when I did try to toggle, using the `alt + T` key on Chrome browser, it opened the `Tools Menu bar`.

## Expected Behavior
Toggle to the dark mode using the combination keys.

## Current Behavior
Open `https://manifest.app` in a tab. Enter the `alt + T` combination stroke. Opens the `Tools Menu bar` on Chrome browser running on Ubuntu 16.04 OS.

## Your Environment

* Environment name and version (nginx 1.9.1):
* Operating System and version: Ubuntu 16.04

**Comment by jonathontoon** [comment]
Hey there @abhijitnathwani, thanks for the report!

Any way you can clarify what the `Tools Menu Bar` is? So far Chrome on Windows and macOS have had no issues and I can't see that shortcut listed on Google's Chrome (for Linux) website. Unless it's something unique to Ubuntu?

Perhaps @pacocoursey has an idea for a more ubiquitous shortcut we could use.

**Comment by abhijitnathwani** [comment]
Hey @jonathontoon 
Thank you for the prompt reply. I am not sure how can I explain the MenuBar behavior. I have tried to demonstrate in this video [here](https://vimeo.com/user107696561/review/385968688/33a56c6ab2). Please have a look.

In general, `alt` triggers the menu operations on any application in `Ubuntu`. I guess the combination needs to be altered.

**Comment by pacocoursey** [comment]
Yeah, it's tough to find a keybind that works across all major browsers. I don't think there's a standard for this.

I chose `t` because of the association with "theme". <kbd>Ctrl</kbd><kbd>T</kbd> won't work on Mac or Windows though, since that's a default for opening a new tab, hence <kbd>Alt</kbd>.

I've seen <kbd>Ctrl</kbd><kbd>I</kbd> used ("invert"), unsure if that avoids overlap with any default browser keybinds.

**Comment by jonathontoon** [comment]
@abhijitnathwani thanks for the video. @pacocoursey hmm `Ctrl+I` could work...

Back when I worked on another project, Tweet Tray, all of the shortcuts ended up having a `Ctrl/CMD + Alt...` prefix just to avoid clashing with existing browser or OS events. It's not pretty but may need to be the approach taken here too.

**Comment by abhijitnathwani** [comment]
yeah, a triple combination key could avoid conflicts. Or could a user select his own `hotkeys` combination for toggling per his OS/browser (seems moonshot though)? @jonathontoon @pacocoursey

**Comment by jonathontoon** [comment]
@abhijitnathwani yeah hotkeys would fragment the experience too much I think. I'll do a bit more research over the weekend and see if we can get a decent, but compromised, shortcut solution.
