### ISSUE TITLE
Add notes with functionality

### ISSUE THREAD

**Issue by IvanMontilla** [jonathontoon/manifest#116]
It'd be nice if notes had functionality. So you can pull up a new note and type in a command and then Manifest reacts on it. E.g.: a ```pull g-drive``` command in a _terminal window_ draws a tree of your files from Google Drive, in such a way the widget loads a new UI/window for manipulating your files, but the _terminal_ disappears. Another e.g.: ```trellocard pending <description>``` command creates a new card on the "Pending" board you have on Trello.

This is one of many commands that can be added. Inspired by the gimmicks of Slack.

## Few commands ideas
- Dim lights of your bedroom.
- View and post on social media.
- Control your Linux boxes.
- View your analytics on your websites.
- Add items to wishlist on Amazon.

## Context
- Taking notes is nice and fun, but what about taking notetaking to the next level?
- Way too many notetaking apps right now, this could be a good differentiator.
- This product could be targeted to many audiences among many industries, tackle one at a time, and then go with the adjacent market.

**Comment by jonathontoon** [comment]
Thanks for the idea @IvanMontillaM but I feel like this is slightly out of the scope of what Manifest should be for. While I love CLI-type interfaces I'm not sure how much value this would add to the product compared to complexity bloat (as for now it's thankfully dependency-free).
