### ISSUE TITLE
Dark Mode does not persist in Safari

### ISSUE THREAD

**Issue by bbdaniels** [jonathontoon/manifest#120]
## Expected Behavior
Dark Mode setting persists on close/reopen of browser or opening of new tabs or windows.

## Current Behavior
Manifest resets to Light Mode after close/reopen of browser window, or any new tab or window, even if not quit.

## Possible Solution
Possible to store setting with content?

## Steps to Reproduce (for bugs)
Open, set, close window, reopen:
![Feb-03-2020 17-52-10](https://user-images.githubusercontent.com/1459122/73698131-4428cd80-46ae-11ea-9fd6-85d019a533b3.gif)

## Your Environment
Safari Version 13.0.5 (15608.5.11)
macOS Catalina Version 10.15.3 Beta (19D75a)

**Comment by jonathontoon** [comment]
Thanks for reporting @bbdaniels. I have my suspicions that trying to fix something on the Catalina Beta should be avoided until it's properly released. However as I'm not running on macOS would you have time to take a peek @pacocoursey?

**Comment by jonathontoon** [comment]
Should be fixed in #127.
