### ISSUE TITLE
Backup support

### ISSUE THREAD

**Issue by MH15** [jonathontoon/manifest#124]
Possible implementation of a way to backup notes to somewhere other than the user's localstorage.

## Expected Behavior
The notes could be written to a github gist, or saved to the user's cloud storage accounts.

## Current Behavior
Currently the notes are only saved to localstorage.

## Possible Solution
In order to match this project's goals to keep dependencies to a minimum, a "save" button could simply allow the user to download a text archive of their notes, which could be imported to the website at a later date.
File Uploads/Downloads are supported easily in all browsers

## Context
The risk/benefit of using a note-taking application is high when you cannot backup notes.

**Comment by jhuescar** [comment]
Hello, 

Unfortunately, I did a cookie deletion on google and deleted all my notes.

Is there any way I can get it back?

I am writing from my Mac.
