### ISSUE TITLE
Some way to import/export all notes/positions etc

### ISSUE THREAD

**Issue by adamcoding** [jonathontoon/manifest#126]
## Expected Behavior
Button to assist in transfer of all notes as a single string suitable for easy import/export.

## Current Behavior
No way to save notes other than in Local Storage.

## Possible Solution
button to uuencode or similar zipped archive of json structures.
or a control window with a menu. toolbox. toolbar. or hide it behind a set of keys.

## Context
Import/Export of notes without requiring a server. Great for todo lists from templates held elsewhere.

## Your Environment
Use uuencode or similar (base64 is built in?) and it could make using on different devices easier without a server. Could have external scripts create lists etc then easily manually import in just by copy & pasting.

**Comment by ebarquero85** [comment]
This feature will make this app excelent.

**Comment by adamcoding** [comment]
I'm digging into feasibility now. I don't see this as necessarily a backup feature although it could easily be used for that. Its more of a import/export. I don't want to pull in any libraries for this if I can manage it. That excludes zip etc as far as I can see but someone else can confirm/deny that. 

Right now I'm thinking of a single UI element like a button at some edge of screen to control import/export. Maybe that brings up a window and some mechanism to choose which individual or all notes to export. Import would replace any existing note with same identity but leave the others alone. 

Internal format would be json with base64 encoding so you just copy/paste big blobs of armored text. To backup you'd export, paste into a text editor then save as a text file. Maybe even provide a export to file feature with today's date/time prefixed into filename.
