### ISSUE TITLE
Service worker offline cache not working

### ISSUE THREAD

**Issue by johncalvinroberts** [jonathontoon/manifest#143]
The service worker is either not properly caching assets, or not properly retrieving cached assets when offline.

## Expected Behavior
When network is not available, the service worker should check the `manifest-1.0.0` appcache for an asset, and serve it from the cache if a match is found.

Original task -- #22, implementation in #69 

## Current Behavior
When network is not available, the app does not load.

## Possible Solution
Pretty sure I have the solution, it's just a missing return value on one of the SW hooks -- will open PR momentarily.

Edit: #143 

## Steps to Reproduce (for bugs)
1. Either run the prod build on local env or visit the production app -> https://www.manifest.app/
2. If in chrome, open devtools -> `application` tab -> `cache storage` -> `manifest-1.0.0` -- confirm assets are being cached
3. Either turn wifi off on your machine, or set `throttling` to `offline` in chrome dev tools
4. Refresh the page
5. Confirm -- page does not load

## Context
I'm working on a similar lightweight utility app, and I checked out the Service Worker implementation on manifest as a reference. Super sick app by the way, huge inspiration!

**Comment by jonathontoon** [comment]
Merged. Thanks again for the fix @johncalvinroberts.
