### ISSUE TITLE
Richtext or Markdown?

### ISSUE THREAD

**Issue by jonathontoon** [jonathontoon/manifest#21]
## Expected Behavior
For richtext:
CMD/Ctrl + B for Bold, CMD/Ctrl + I for Italic, CMD/Ctrl + U for Underline, CMD/Ctrl + S for Strikethrough.

Markdown:
The best solution here would have to be in-line markdown syntax. Some thing like IA Writer or similar.

## Current Behavior
Plain text only. 😢

**Comment by adamlaz** [comment]
you're super lightweight right now, so I feel bad suggesting this but I absolutely love [the Quil editor](https://quilljs.com/docs/). It'd be straight forward to then add some shortcuts using [their Keyboard module](https://quilljs.com/docs/modules/keyboard/#keyboard-module).

**Comment by januwland** [comment]
+1 for URLs to link

**Comment by elton2048** [comment]
Support for Markdown

**Comment by MH15** [comment]
I'd be up to make these changes and contribute Markdown support. I'm thinking of a toggle (or dropdown) in the heading on a note that can choose what type of processor to use.

If anyone has any suggestions or comments on this let me know.

Edit: pending the creator's approval of course.

**Comment by jonathontoon** [comment]
More than happy to review any ideas @MH15. At this stage however I think it's we either have in-line markdown syntax support (like iA Writer and it's derivatives) or stick with plain text. I'm curious to hear more about your idea of selecting a processor?

**Comment by MH15** [comment]
I've been busy with work and uni but currently my plan was to simply allow user input in the same format as before (plain text) then if an option (checkbox or switch) is enabled, when you focus out of the note it displays rendered markdown. Thoughts?
