### ISSUE TITLE
Initiating drag but not moving new memos moves them to the top-left corner of the grid

### ISSUE THREAD

**Issue by Hyperseeker** [jonathontoon/manifest#30]
## Expected Behavior

"Cancelling" drag on new memos should result in them remaining where they were created.

## Current Behavior

See title.
Once the memo has been dragged to any position once, it will no longer jump back to X0/Y0.

## Possible Solution

See if `top` or `left` in `/src/js/classes/memoElement.js → _handleDragStart()` returns a falsy value due to failing to `snapToGrid()` on first non-drag.

## Steps to Reproduce (for bugs)

1. create memo
2. click dragbar
3. look at it go

**Comment by jonathontoon** [comment]
Thanks for filing, I'm trying to reproduce this myself, but I'm failing to on the latest build (here's a gif).
Are you able to cancel a drag in some other way, perhaps I've missed an edge case? Also if you could add your browser spec and version too that may help me figure it out.

![](https://i.imgur.com/ukCZtmh.gif)

**Comment by Hyperseeker** [comment]
I can no longer replicate the issue myself, either. The memos created in the latest version at manifest.app are not affected by this. Could it be that they're fixed, in a roundabout way, by having a default memo up on initialization?

Feel free to close this. If there's ever another version of the bug, I'll report on it in a separate issue.

**Comment by jonathontoon** [comment]
Sweet mate thanks any way.
