### ISSUE TITLE
Memos can be resized to levels where they become inoperable

### ISSUE THREAD

**Issue by Hyperseeker** [jonathontoon/manifest#53]
## Expected Behavior

I think memos should have a minimum size below which they can't be resized, regardless of the content they hold.
If they hold more content than their frame suggests, there should be a way to reach all of said content.

## Current Behavior

![see screenshot](https://user-images.githubusercontent.com/7418445/72048913-6d914c00-32f0-11ea-99e2-200e1f396112.png)

## Possible Solution

1. minimum height for one line to be visible at all times
2. scrolling to for collapsed notes that have more content than their size would suggest?
3. minimum width of a few characters
4. placeholders based on width/height of the empty memo ("Add a short memo..." → "Add a memo..." → "Write..."), via classes that are calculated per memo-resize event

## Steps to Reproduce (for bugs)

1. try to resize a memo
2. go just a little too far with it
3. mess up the UI of an app you haven't even touched the CSS of

## Context

I understand the need to resize notes in free-floating note-taking apps. Sometimes, users might want to go to extremes with their notes for the sake of satisfying their personal preferences.

As a developer – and, coincidentally, as a developer of a side project that's similar in purpose – I consider that there are lines to be drawn. Notes must remain at least partially readable at any given moment. Users may make mistakes with the app, and it's the designer's job to make sure these mistakes are few, far between, and ultimately fixable.

On-resize calculations for width, height, and grid-snapping are not expensive. There may even be a CSS solution (perhaps setting `min-height` might work?), which would be even more efficient.

Perhaps even – and this is me dreaming aloud – set memos' width and height via their grid alignment: so that a memo can have attributes of `data-height="3"` and `data-width="7"`, which could be combined with pre-calculated grid section sizes to calculate the memo's viewport width. (How this is beneficial to this particular problem, I'm failing to see, either, but it dawned upon me, and I had to share.)

## Your Environment

* Browser name and version: Cent Browser, Version 4.0.9.112 (based on Chromium 74.0.3729.169)
* Operating System and version: Windows 10 LTSC

**Comment by jonathontoon** [comment]
@FirebrandCoding good catch, I just came on here to file this myself.
