### ISSUE TITLE
Allow users to create memos of fixed size via clicking

### ISSUE THREAD

**Issue by Hyperseeker** [jonathontoon/manifest#58]
## Expected Behavior

Clicking is much easier and faster than dragging. The assumption is that some users may not need to define the memos' sizing before they'd even started the note-taking process. Quickly creating a memo to write in may serve that process better by eliminating unnecessary middle-layer interactions.

## Possible Solution

While it's easy to assume that most devices are going to have wide aspect ratio, this isn't necessarily true. Old monitors and mobile devices offer a different view on the grid, where creating long-by-default memos may hamper the experience.

The proposal is to have a certain set of limits (for example, a quick-created memo cannot be taller than 8 grid lines or wider than 8 grid lines), and orient within those limits based on device aspect ratio. If the device is wider, allow quick memos to be the maximum width on creation but limit their default height.

For a rough estimate, a 16:9 device would probably make a quick memo that's 8 lines wide and 4 lines tall. iPhone 5 (with its 16:9 screen) in portait mode would have memos 4 lines wide and 8 lines tall, conversely. (The quick calculation being `Math.floor(aspect / 2)`.)

Larger devices may default to larger maximums, and vice versa.

That said, I'm pretty sure it's better to initially allow creating memos of a fixed size, regardless of aspect ratio or screen size, and progressively update into a more considerate process once time allows. Clicking is the better default, and improving defaults is more important than getting them right on the first try.

**Comment by jonathontoon** [comment]
Thanks for the feedback @FirebrandCoding. I've been thinking about this for a couple of days and my answer for the time being is that I will shelve it for now.

The main two reasons for are:

1. I think that requiring an intent driven interaction, such as clicking and dragging, to create a memo helps re-enforce the whole point of the grid system and the idea of organizing ideas spatially.

2. If you could create a default memo simply by clicking/tapping it would open up the possibility of a lot of false positives and mistakes. The way to remedy this would be introducing a concept of an explicit drawing/memo creation mode, which I don't think is worth the cost, nor does it provide a simpler experience than what we have right now.

Feel free to continue discussing potential ideas, but I'll close this for now.
