### ISSUE TITLE
Right clicking when creating a memo breaks the interaction

### ISSUE THREAD

**Issue by jonathontoon** [jonathontoon/manifest#61]
## Expected Behavior
If I right click it just cancels the event and no memo is drawn.

## Current Behavior
You're left with a grey square on the board that you can't get rid of.

**Comment by Hyperseeker** [comment]
Being able to cancel the memo creation in-process is a good thing, especially considering that you can't Ctrl+Z them away afterwards. Yes, you can click the `-` after it's created, but if the creation wasn't wanted – bacause, for example, the user wanted to focus on something else amid the drag – it created friction.

Right-clicking or pressing Escape are solid options for cancelling.

**Comment by jonathontoon** [comment]
Fixed in #69 so only left click, or touches will initiate a draw. Other mouse inputs are ignored.
