### ISSUE TITLE
Grid misalignment

### ISSUE THREAD

**Issue by jonathontoon** [jonathontoon/manifest#67]
## Expected Behavior
To align to the grid.

## Current Behavior

![misalign](https://user-images.githubusercontent.com/1197942/72211357-15d82800-351e-11ea-9d17-899749835290.PNG)

**Comment by afk-mario** [comment]
Just to add to this 

![image](https://user-images.githubusercontent.com/1025751/72212501-141d4e80-34a3-11ea-87ca-ea0ecc241249.png)

using:

Mozilla Firefox Developer Edition 73.0b2 (64-bit)
OS: Arch linux

**Comment by jonathontoon** [comment]
Grid alignment is back to a working order. In order to get it to work you _may_ need to clear your local storage.

![grid](https://user-images.githubusercontent.com/1197942/72234978-caa83d00-3623-11ea-9bac-1cada58fc1c5.PNG)
