### ISSUE TITLE
Text that overflows a note is not scrollable.

### ISSUE THREAD

**Issue by tdjsnelling** [jonathontoon/manifest#68]
If the text is long enough to overflow a note, a user is unable to scroll the content and it gets cut off.

## Expected Behavior
Should be able to scroll and see the cut off content.

## Current Behavior
Unable to scroll and see the cut off content.

## Possible Solution
[This line](https://github.com/jonathontoon/manifest/blob/master/src/sass/index.scss#L71) can be switched for `overflow-x: hidden` to ensure overflowing content in the Y direction can still be scrolled.

## Your Environment
* Windows 10
* Chrome 79.0.3945.117

**Comment by jonathontoon** [comment]
Thanks a lot for reporting. I think some kind of custom styled scroll bar may be required as on Windows the scroll bar will be chunky and not so nice.

**Comment by jonathontoon** [comment]
Implemented a scrollable textarea with a minimal scroll bar indicator.

![scroll](https://user-images.githubusercontent.com/1197942/72235035-ff1bf900-3623-11ea-82d9-4e0d7a5e3951.PNG)
