### ISSUE TITLE
Restrict memos being dragged outside of the grid.

### ISSUE THREAD

**Issue by jonathontoon** [jonathontoon/manifest#7]
## Expected Behavior
I should be stopped if I try to drag a memo outside of grid bounds.

## Current Behavior
I can drag anywhere.

**Comment by jonathontoon** [comment]
Should this even be an issue? 🤔

**Comment by Hyperseeker** [comment]
You can no longer re-drag or close a memo that's been dragged too far to the top off the grid.

![For example...](https://user-images.githubusercontent.com/7418445/71962699-9c45ee80-322c-11ea-9d96-78278adcb6ee.png)

Definitely a bug.

My suggestion is to check for `top` / `left` values on drag and set them to 0 if they're below that (i.e. if if they're too far up /to the left) or to `grid height - memo height` / `grid width - memo width` for the opposite case (i.e. too far down / to the right).

**Comment by jonathontoon** [comment]
@FirebrandCoding good catch. Will do something about it.

**Comment by jonathontoon** [comment]
Partial fix is now deployed in to Master. Only handles one axis at a time for now. But it gets us most the way there. Will need to refactor things a little bit later to handle multiple axes at once. Moving to milestone v1.1.1 for now.

**Comment by pachacamac** [comment]
This might be related: If you create a memo on a certain resolution / window size and then change the resolution or window size, some memos are not visible anymore. My suggestion would be to show scroll bars in order to enable users to still see all memos without having to reshuffle them.

**Comment by vonnieda** [comment]
I think @pachacamac's comment is actually the bigger issue. There's no way to know if I have notes off in some direction because of a large window I used at one point.

**Comment by pachacamac** [comment]
Changing https://github.com/jonathontoon/manifest/blob/master/src/sass/index.scss#L13 (body overflow: hidden) to overflow: auto, kind of fixes the problem, however the dotted grid is only drawn on the visible screen.

**Comment by jonathontoon** [comment]
@pachacamac at this stage I haven't found a solution I like beyond creating an infinite canvas, which won't happen for the current version of Manifest. Someone else might have a creative method we could employ but at present it's simply one of the limitations of the app.

**Comment by pachacamac** [comment]
@jonathontoon totally understand. But how about making a shortcut or button to toggle overflow: hidden/auto? This way the user can at least access notes when switching to a smaller screen, even though it's not as pretty or sophisticated as a true infinite canvas with zooming etc?

**Comment by jonathontoon** [comment]
@pachacamac I'd rather not create too many toggles or shortcut queues that people would need to learn. I think your initial idea of having a scrollable canvas actually _could_ work well. Would just need to figure out the max possible resolution of the browser and then create a parent container to mask the canvas. An infinite canvas is a better solution, but this could suffice as a hack.
