### ISSUE TITLE
Drawing with Manifest?

### ISSUE THREAD

**Issue by jonathontoon** [jonathontoon/manifest#70]
## Expected Behavior
Would drawing be a useful tool to compliment things?

## Current Behavior
Currently it's just memos, which aren't always the best way to express things.

## Possible Solution
The real deal breaker for me here is whether it would be grid-based or free form. Making it free might break the zen quality the current version has right now. Although grid-based might not be that useful? I'm also worried that creating memos and drawing would introduce specific modes for each tool, which I really think messes with the simplicity of things right now...

Need to think about this some more...

**Comment by Immortalin** [comment]
Take a look at how Figma implements it. You can have both.

**Comment by adamlaz** [comment]
Maybe instead of typing in the box that is made, a user can decide to draw/sketch?
