### ISSUE TITLE
Feature Suggestion → Dark Mode

### ISSUE THREAD

**Issue by jdsimcoe** [jonathontoon/manifest#95]
It would be awesome to have a dark mode that uses CSS's built-in `@media (prefers-color-scheme: dark)` method to automatically switch themes based on the operating system settings:

https://css-tricks.com/dark-modes-with-css/

**Comment by jonathontoon** [comment]
Might need to do a little refactoring as currently some color styles are being applied specifically in JS, but excellent idea. Shouldn't be too hard.

**Comment by jdsimcoe** [comment]
@jonathontoon this is fantastic!
